pipeline{
    agent {
      node {
             label 'test'
        }
    }

    environment{
        PR_CREDENTIALS_ID = "PR_CONSUMER_KEY"
    }

    stages{
        stage("Code analysis"){
            steps{
                script {
                    sh "chmod +x test/bashScripts/countError.sh"
                    sh "./test/bashScripts/countError.sh"
                    echo "PMD Script - Commit at develop"
                }
            }
        }
        stage("Validate"){
           steps {
                script {
                     if (env.CHANGE_ID != null){
                        if (env.CHANGE_TARGET == 'QA') {
                            withCredentials([usernamePassword(credentialsId: "${PR_CREDENTIALS_ID}", passwordVariable: 'PR_CONSUMER_KEY', usernameVariable: 'PR_USERNAME')]) {
                                echo "  "
                                echo "Authenticating in Production.... ⏱️"
                                echo " "
                                sh """
                                    pwd 
                                    whoami
                                    sudo wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
                                    mkdir -p ~/cli/sf
                                    tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
                                    export PATH=~/cli/sf/bin:$PATH
                                    PATH=~/cli/sf/bin:$PATH
                                    sf -v 
                                """
                                sh "sudo sf login org jwt --alias PR --client-id ${PR_CONSUMER_KEY} --jwt-key-file accesskey/server.key --set-default --set-default-dev-hub --instance-url https://login.salesforce.com --username ${PR_USERNAME}"
                                echo " "
                                echo "Successfully authenticated in Production ✅"
                                echo " "
                                echo "Validation started ... 🔜"
                                sh "sudo sf project deploy start -x manifest/package.xml --dry-run --target-org PR --ignore-warnings --verbose"
                            }
                        }
                    }
                }
           }
        }
    }
}



