pipeline{
    agent {
      node {
             label 'test'
        }
    }

    environment{
        PR_CREDENTIALS_ID = "PR_CONSUMER_KEY"
        PATH = "${env.PATH}:~/cli/sf/bin"
    }

    stages{
        stage("Code analysis"){
            steps{
                script {
                    sh "chmod +x test/bashScripts/countError.sh"
                    sh "./test/bashScripts/countError.sh"
                    echo "PMD Script - Commit at develop"
                }
            }
        }
        stage("Validate"){
           steps {
                script {
                     if (env.CHANGE_ID != null){
                        if (env.CHANGE_TARGET == 'QA') {
                            withCredentials([usernamePassword(credentialsId: "${PR_CREDENTIALS_ID}", passwordVariable: 'PR_CONSUMER_KEY', usernameVariable: 'PR_USERNAME')]) {
                                echo "  "
                                echo "Authenticating in Production.... ⏱️"
                                echo " "
                                sh """
                                    export PATH=~/cli/sf/bin:$PATH
                                    PATH=~/cli/sf/bin:$PATH
                                    sf -v 
                                    sf login org jwt --alias PR --client-id ${PR_CONSUMER_KEY} --jwt-key-file test/accesskey/server.key --set-default --set-default-dev-hub --instance-url https://login.salesforce.com --username ${PR_USERNAME}
                                    Successfully authenticated in Production ✅
                                    Validation started ... 🔜
                                    sf project deploy start -x test/manifest/package.xml --dry-run --target-org PR --ignore-warnings --verbose
                                """
                            }
                        }
                    }
                }
           }
        }
    }
}



